version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          paths:
            - dist
          key: v1-dist-{{ .Branch }}-{{ .Revision }}

  test:
    docker:
      - image: circleci/node:10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:10.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v1-dist-{{ .Branch }}-{{ .Revision }}
      - add_ssh_keys:
          fingerprints:
            - "ec:d6:e5:9f:8f:58:5e:d9:11:6b:3b:82:f6:ef:56:1b"
      - run: >
          git config --global -l
          git config --global user.email circleci@circleci
          git config --global user.name CircleCI
      - run: ./scripts/publish.sh

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - /release\/.*/